name: S3S-CNN
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pytorch::pytorch=2.0.0
  - pytorch::torchaudio=2.0.0
  - pytorch::torchvision=0.15.0
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyqt
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip:
    - opencv-python-headless