name: S3S-CNN
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - nvidia::cudatoolkit=11.3.1
  - pytorch::pytorch=1.12.1
  - pytorch::torchaudio=0.12.1
  - pytorch::torchvision=0.13.1
  - ipykernel=6.15.1
  - matplotlib=3.5.1
  - numpy=1.23.1
  - pandas=1.4.3
  - pip=22.2.2
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.11.2
  - tqdm=4.64.0
  - pip:
    - opencv-python-headless=4.6.0.66