name: S3S-CNN
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip:
    - opencv-python-headless